### ISSUE TITLE
Is this supposed to happen?

### ISSUE THREAD

**Issue by kunalmunjal** [pmurpmur/BadgerScalp#14]
I am not sure if it happens to other devices or not, but whenever I type in the Ip, it doesn't load.
![img_0663](https://cloud.githubusercontent.com/assets/6073351/11603973/6eb448f2-9aac-11e5-84d4-24a2419980b4.PNG)

**Comment by pmurpmur** [comment]
I am not sure what you are trying to do exactly but we are not hosting this application in any way. To run this app you either have to run it in browser via 'ionic serve' or build the app and install it on your phone. I am going to close this issue but let me know if I misunderstood!
