### ISSUE TITLE
The Take a pic/choose from Album isn't working

### ISSUE THREAD

**Issue by kunalmunjal** [pmurpmur/BadgerScalp#15]
Again, on a Google chrome, windows 8 x64. These options aren't working, I am not sure of iOS or Android...
![2](https://cloud.githubusercontent.com/assets/6073351/11604002/e18ffaec-9aac-11e5-8822-33e355597ec4.png)

**Comment by pmurpmur** [comment]
You will not be able to take pictures unless you are on phone. so this is okay
