### ISSUE TITLE
iOS keyboard blocks account creation fields

### ISSUE THREAD

**Issue by AZaruba** [pmurpmur/BadgerScalp#6]
When creating a new account on iOS, entering the first name and last name are fine (in portrait orientation) but the keyboard blocks the email and password fields. I am unable to scroll the page down like on most other mobile websites.

Everything enters correctly, it just is very inconvenient!
![img_1098](https://cloud.githubusercontent.com/assets/11434471/11578520/181c2674-99ec-11e5-9a3b-e24dd23f7f7a.PNG)

**Comment by pmurpmur** [comment]
Good to know! allowed scrolling during authorization and committed to development branch
